# Synthetic Data Generation for RAG Evaluation

Session 1 built a vector RAG application over a cat health guideline PDF. This
session creates an evaluation dataset for that application and uses the dataset
to compare two retrieval configurations. All generation, embedding, RAG, and
judge requests are routed through Vercel AI Gateway.

The workflow is:

~~~text
corpus -> knowledge graph -> synthetic examples -> human review
       -> LangSmith dataset -> baseline and candidate experiments
~~~

Synthetic examples reduce the cost of getting started, but generated references
are not automatically ground truth. We will inspect and curate them before using
them as evaluation targets.

> This is an educational cat health exercise, not veterinary advice. Generated
> questions and answers must not be used to diagnose, prescribe, or replace a
> veterinarian.

## Learning Outcomes

By the end of this notebook, you will be able to:

- Explain how Ragas builds a knowledge graph for test data generation.
- Distinguish single-hop specific, multi-hop specific, and multi-hop abstract queries.
- Generate and review synthetic questions, reference contexts, and reference answers.
- Route generation, embeddings, RAG, and judge calls through Vercel AI Gateway.
- Upload reviewed examples to a LangSmith dataset.
- Evaluate answer correctness, answer groundedness, and retrieval relevance.
- Run a controlled RAG experiment that changes one variable at a time.

## Table of Contents

- **Breakout Room #1: Synthetic Test Data with Ragas**
  - Task 1: Environment Setup
  - Task 2: Load the Cat Health Corpus
  - Task 3: Build and Enrich a Knowledge Graph
  - Task 4: Inspect the Query Distribution
  - Task 5: Generate and Inspect a Synthetic Test Set
  - Activity #1: Review and Curate the Dataset
- **Breakout Room #2: RAG Evaluation with LangSmith**
  - Task 6: Create a LangSmith Dataset
  - Task 7: Build a Baseline RAG Application
  - Task 8: Define RAG Evaluators
  - Task 9: Run the Baseline Experiment
  - Task 10: Change One Retrieval Variable and Re-Evaluate
  - Activity #2: Compare, Diagnose, and Iterate
  - Advanced Build: Add Robustness and Adversarial Cases

---
# Breakout Room #1
## Synthetic Test Data with Ragas

Ragas uses the source corpus to create a richer representation of its topics and
relationships. Query synthesizers then select scenarios from that representation
and generate questions plus reference answers.

The knowledge graph is a generation aid. It is not the graph used by the RAG
application in Breakout Room #2.

## Task 1: Environment Setup

From the <code>05_Synthetic_Data_Generation_for_RAG_Evals</code> folder:

~~~bash
uv sync
~~~

Then select the environment created by uv as this notebook's kernel.

Required accounts:

- Vercel AI Gateway for generation, embeddings, the RAG answer model, and judges
- LangSmith for the dataset and experiments

A direct OpenAI API key is not required. The OpenAI SDK is used only as a
protocol-compatible client pointed at Vercel AI Gateway.

The default synthetic test set is intentionally small. Ragas generation and
LLM-as-judge evaluation both make multiple model calls, so start small and scale
only after inspecting quality.

### Imports

In [41]:
from __future__ import annotations

import os
from collections import Counter
from getpass import getpass
from importlib.metadata import version
from pathlib import Path
from uuid import uuid4

import instructor
from IPython.display import display
from openai import OpenAI
from pydantic import BaseModel, field_validator

from langchain_community.document_loaders import PyPDFLoader
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_qdrant import QdrantVectorStore
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langsmith import Client, evaluate
from openevals.llm import create_llm_as_judge
from openevals.prompts import (
    CORRECTNESS_PROMPT,
    RAG_GROUNDEDNESS_PROMPT,
    RAG_RETRIEVAL_RELEVANCE_PROMPT,
)

from ragas.embeddings.base import embedding_factory
from ragas.llms import llm_factory
from ragas.run_config import RunConfig
from ragas.testset import TestsetGenerator
from ragas.testset.graph import KnowledgeGraph, Node, NodeType
from ragas.testset.synthesizers import (
    MultiHopAbstractQuerySynthesizer,
    MultiHopSpecificQuerySynthesizer,
    SingleHopSpecificQuerySynthesizer,
    default_query_distribution,
)
from ragas.testset.transforms import (
    CustomNodeFilter,
    SummaryExtractor,
    apply_transforms,
    default_transforms_for_prechunked,
)

### API Keys, Models, and Cost Controls

The notebook reads model names and budgets from environment variables so you can
tune cost without editing every cell. Vercel AI Gateway exposes an
OpenAI-compatible endpoint, so the OpenAI and LangChain clients only need a
different API key, base URL, and provider-qualified model ID.

See the [Vercel AI Gateway Python documentation](https://vercel.com/docs/ai-gateway/sdks-and-apis/python)
for the current authentication and endpoint details.

LangSmith uses <code>LANGSMITH_TRACING</code>. The older
<code>LANGCHAIN_TRACING_V2</code> name from the source notebook is no longer
needed here.

In [42]:
gateway_api_key = (
    os.environ.get("AI_GATEWAY_API_KEY")
    or os.environ.get("VERCEL_OIDC_TOKEN")
)

if not gateway_api_key:
    gateway_api_key = getpass("Vercel AI Gateway API Key: ")
    os.environ["AI_GATEWAY_API_KEY"] = gateway_api_key

if not os.environ.get("LANGSMITH_API_KEY"):
    os.environ["LANGSMITH_API_KEY"] = getpass("LangSmith API Key: ")

os.environ.setdefault("LANGSMITH_TRACING", "true")
os.environ.setdefault(
    "LANGSMITH_PROJECT",
    "aim-session-5-synthetic-rag-evals",
)

GATEWAY_BASE_URL = os.environ.get(
    "AI_GATEWAY_BASE_URL",
    "https://ai-gateway.vercel.sh/v1",
)
GENERATOR_MODEL_NAME = os.environ.get(
    "AIM_GENERATOR_MODEL",
    "openai/gpt-5.4-mini",
)
RAG_MODEL_NAME = os.environ.get(
    "AIM_RAG_MODEL",
    "openai/gpt-5.4-mini",
)
JUDGE_MODEL_NAME = os.environ.get(
    "AIM_JUDGE_MODEL",
    "openai/gpt-5.4-mini",
)
EMBEDDING_MODEL_NAME = os.environ.get(
    "AIM_EMBEDDING_MODEL",
    "openai/text-embedding-3-small",
)
TESTSET_SIZE = int(os.environ.get("AIM_TESTSET_SIZE", "6"))
MAX_CONCURRENCY = int(os.environ.get("AIM_MAX_CONCURRENCY", "2"))

gateway_models = {
    "generator": GENERATOR_MODEL_NAME,
    "rag": RAG_MODEL_NAME,
    "judge": JUDGE_MODEL_NAME,
    "embedding": EMBEDDING_MODEL_NAME,
}
for role, model_name in gateway_models.items():
    if "/" not in model_name:
        raise ValueError(
            f"{role} model must use a provider-qualified AI Gateway ID: "
            f"{model_name!r}"
        )

print(f"Ragas: {version('ragas')}")
print(f"LangSmith: {version('langsmith')}")
print(f"AI Gateway: {GATEWAY_BASE_URL}")
print(f"Generator model: {GENERATOR_MODEL_NAME}")
print(f"RAG model: {RAG_MODEL_NAME}")
print(f"Judge model: {JUDGE_MODEL_NAME}")
print(f"Embedding model: {EMBEDDING_MODEL_NAME}")
print(f"Synthetic examples: {TESTSET_SIZE}")
print(f"LangSmith tracing: {os.environ['LANGSMITH_TRACING']}")

Ragas: 0.4.4.dev8+g298b68274
LangSmith: 0.8.16
AI Gateway: https://ai-gateway.vercel.sh/v1
Generator model: openai/gpt-5.4-mini
RAG model: openai/gpt-5.4-mini
Judge model: openai/gpt-5.4-mini
Embedding model: openai/text-embedding-3-small
Synthetic examples: 6
LangSmith tracing: true

## Task 2: Load the Cat Health Corpus

The corpus is the bundled 2021 AAHA/AAFP Feline Life Stage Guidelines PDF used
in Session 1. <code>PyPDFLoader</code> extracts one LangChain document per page,
including page metadata that survives later chunking.

This gives the generator multiple related units to connect:

- hydration and urinary signs
- preventive care and senior care
- dental pain and behavior changes
- monitoring and emergency escalation

In [43]:
corpus_path = Path("data/cat_health_guidelines.pdf")

if not corpus_path.exists():
    raise FileNotFoundError(
        f"Expected the course corpus at {corpus_path.resolve()}"
    )

pdf_loader = PyPDFLoader(str(corpus_path))
source_documents = pdf_loader.load()
source_documents = [
    document
    for document in source_documents
    if len(document.page_content.strip()) >= 200
]

for index, document in enumerate(source_documents):
    page_number = int(document.metadata.get("page", index)) + 1
    document.metadata.update(
        {
            "source": corpus_path.name,
            "document_type": "feline_life_stage_guidelines",
            "page_number": page_number,
        }
    )

print(f"Loaded {len(source_documents)} text-containing PDF pages")
for document in source_documents[:5]:
    page_number = document.metadata["page_number"]
    print(
        f"- page {page_number}: "
        f"{len(document.page_content)} characters"
    )

Loaded 20 text-containing PDF pages
- page 1: 4913 characters
- page 2: 2084 characters
- page 3: 5955 characters
- page 6: 5673 characters
- page 7: 3588 characters

Inspect one PDF page and its metadata. The metadata is useful for debugging,
trace inspection, and explaining where a retrieved chunk came from.

In [44]:
sample_document = source_documents[0]

print(sample_document.metadata)
print()
print(sample_document.page_content[:800])

{'producer': 'Acrobat Distiller 10.0.0 (Windows)', 'creator': 'Adobe InDesign CS6 (Windows)', 'creationdate': '2021-02-02T08:52:15-05:00', 'author': '7123', 'moddate': '2021-02-02T07:53:51-07:00', 'title': 'djs_jaaha_56_5_COVER.indd', 'source': 'cat_health_guidelines.pdf', 'total_pages': 22, 'page': 0, 'page_label': '1', 'document_type': 'feline_life_stage_guidelines', 'page_number': 1}

VETERINARY PRACTICE GUIDELINES
2021 AAHA/AAFP Feline Life Stage Guidelines*
Jessica Quimby, DVM, PhD, DACVIM y, Shannon Gowland, DVM, DABVP y, Hazel C. Carney, DVM, MS, DABVP,
Theresa DePorter, DVM, MRCVS, DACVB, DECAWBM, Paula Plummer, LVT, VTS (ECC, SAIM), Jodi Westropp,
DVM, PhD, DACVIM
ABSTRACT
The guidelines, authored by a Task Force ofexperts in feline clinical medicine, are an update and extension of the AAFP–AAHA
Feline Life Stage Guidelines published in 2010. The guidelines are published simultaneously in theJournal of Feline Medicine and
Surgery(volume 23, issue 3, pages 211–233, DOI: 10.1177/1098612X21993657) and theJournal of the American Animal Hospital
Association(volume 57, issue 2, pages 51–72, DOI: 10.5326/JAAHA-MS-7189). A noteworthy change from the earlier guidelines is

## Task 3: Build and Enrich a Knowledge Graph

The unrolled workflow makes the generation stages visible:

1. Treat each text-containing PDF page as a pre-chunked Ragas node.
2. Run Ragas extractors, embeddings, and relationship builders.
3. Save the graph so expensive enrichment can be reused.

Ragas remains responsible for graph enrichment and synthetic generation. The
newer pinned Ragas build exposes an official Instructor mode parameter, so its
LLM factory can use AI Gateway tool calls directly without custom wrappers.

In [31]:
gateway_client = OpenAI(
    api_key=gateway_api_key,
    base_url=GATEWAY_BASE_URL,
)

"""
The Generator LLM creates:

    Questions
Ground-truth answers
Synthetic evaluation examples

"""

generator_llm = llm_factory(
    GENERATOR_MODEL_NAME,
    provider="openai",
    client=gateway_client,
    mode=instructor.Mode.TOOLS,
    max_tokens=4096,
)
# Provider-qualified Gateway IDs bypass Ragas's GPT-5 parameter detection.
# Keep only the token limit supported by the Gateway route. max_retries is
# consumed locally by Instructor and is not sent to AI Gateway.
generator_llm.model_args = {
    "max_tokens": 4096,
    "max_retries": 3,
}

generator_embeddings = embedding_factory(
    "openai",
    model=EMBEDDING_MODEL_NAME,
    client=gateway_client,
)

ragas_run_config = RunConfig(
    timeout=180,
    max_retries=3,
    max_wait=30,
    max_workers=MAX_CONCURRENCY,
)

Before building the graph, make one small structured-output request through
Ragas. This catches gateway authentication, model availability, and tool-calling
incompatibilities without waiting for every PDF page to retry.

In [32]:
class GatewayToolCallCheck(BaseModel):
    status: str


class NonEmptySummary(BaseModel):
    text: str

    @field_validator("text")
    @classmethod
    def require_text(cls, value):
        value = value.strip()
        if not value:
            raise ValueError("summary text cannot be empty")
        return value


gateway_check = generator_llm.generate(
    "Use the required tool with a short, non-empty status message.",
    GatewayToolCallCheck,
)
if not gateway_check.status.strip():
    raise RuntimeError("AI Gateway returned an empty tool-call check")

print(f"AI Gateway tool-based structured output: {gateway_check.status}")

AI Gateway tool-based structured output: checking

In [33]:
def build_prechunked_knowledge_graph(chunks):
    return KnowledgeGraph(      
        nodes=[
            Node(
                type=NodeType.CHUNK,
                properties={
                    "page_content": chunk.page_content,
                    "document_metadata": dict(chunk.metadata),
                },
            )
            for chunk in chunks
            if chunk.page_content.strip()
        ]
    )


generation_chunks = list(source_documents)
knowledge_graph = build_prechunked_knowledge_graph(generation_chunks)

print(f"Ragas input chunks: {len(generation_chunks)}")
print(knowledge_graph)

Ragas input chunks: 20
KnowledgeGraph(nodes: 20, relationships: 0)

### Apply Ragas Transforms

Because the PDF loader already gives us coherent page-level chunks, use Ragas'
built-in pre-chunked transform pipeline. It skips headline extraction and
splitting, then applies Ragas summaries, embeddings, themes, named entities,
and relationship builders directly to the PDF pages. The parent-child node
filter is omitted because these page chunks intentionally have no parent nodes.
A non-empty output constraint makes Instructor retry blank Ragas summaries before
the built-in embedding transform runs.

What is a Transform?

A transform is a processing step applied to the graph.

Knowledge Graph (raw chunks) -> Transforms -> Knowledge Graph (enriched)


Example: 
Chunk:
"Cats should receive annual rabies vaccinations."

After Transform:
Chunk:
"Cats should receive annual rabies vaccinations."

Entities:
- Cats
- Rabies
- Vaccination

In [34]:
knowledge_graph = build_prechunked_knowledge_graph(generation_chunks)

# default_transforms_for_prechunked is a function that returns a list of transforms. 
# It takes a generator_llm and a generator_embeddings as arguments. Some transforms require reasoning so llm is passed
# Some transforms need semantic similarity so embedding_model is passed.
transforms = [
    transform
    for transform in default_transforms_for_prechunked(
        llm=generator_llm,
        embedding_model=generator_embeddings,
    )
    if not isinstance(transform, CustomNodeFilter)
]

# For summary transform, we need to set the output model to NonEmptySummary.
# This is because the summary transform returns a string, but we need a structured output.

summary_transform = next(
    transform
    for transform in transforms
    if isinstance(transform, SummaryExtractor)
) 
summary_transform.prompt.output_model = NonEmptySummary

print("Ragas transform pipeline:")
for transform in transforms:
    nested = getattr(transform, "transformations", None)
    if nested is None:
        print(f"- {type(transform).__name__}")
    else:
        names = ", ".join(type(item).__name__ for item in nested)
        print(f"- Parallel({names})")

for transform in transforms:
    apply_transforms(
        knowledge_graph,
        transform,
        run_config=ragas_run_config,
    )
    if isinstance(transform, SummaryExtractor):
        empty_summary_nodes = [
            node
            for node in knowledge_graph.nodes
            if not str(node.get_property("summary") or "").strip()
        ]
        if empty_summary_nodes:
            raise RuntimeError(
                "Ragas did not produce non-empty summaries for "
                f"{len(empty_summary_nodes)} PDF chunks"
            )

print(knowledge_graph)

Ragas transform pipeline:
- SummaryExtractor
- Parallel(EmbeddingExtractor, ThemesExtractor, NERExtractor)
- Parallel(CosineSimilarityBuilder, OverlapScoreBuilder)

Applying SummaryExtractor: 100%|██████████| 20/20 [00:34<00:00,  1.73s/it]
Applying [EmbeddingExtractor, ThemesExtractor, NERExtractor]:   0%|          | 0/60 [00:00<?, ?it/s]/Users/saurabh3981/Desktop/agenticai/code/AIEC1/05_Synthetic_Data_Generation_for_RAG_Evals/.venv/lib/python3.14/site-packages/ragas/testset/transforms/base.py:198: UserWarning: Using sync embedding model OpenAIEmbeddings in async context. This may impact performance. Consider using an async-compatible embedding model for better performance.
  property_name, property_value = await self.extract(node)
Applying [EmbeddingExtractor, ThemesExtractor, NERExtractor]: 100%|██████████| 60/60 [01:06<00:00,  1.11s/it]
Applying [CosineSimilarityBuilder, OverlapScoreBuilder]: 100%|██████████| 2/2 [00:00<00:00, 176.27it/s]

KnowledgeGraph(nodes: 20, relationships: 51)

Inspect the graph at a high level. Different Ragas versions may add different
properties, so the notebook avoids depending on one exact internal schema.

In [35]:
node_type_counts = Counter(str(node.type) for node in knowledge_graph.nodes)

print("Node types:")
for node_type, count in node_type_counts.items():
    print(f"- {node_type}: {count}")

print(f"Relationships: {len(knowledge_graph.relationships)}")

for index, node in enumerate(knowledge_graph.nodes[:3], start=1):
    property_names = sorted(node.properties.keys())
    print(f"Node {index} properties: {property_names}")

Node types:
- NodeType.CHUNK: 20
Relationships: 51
Node 1 properties: ['document_metadata', 'entities', 'page_content', 'summary', 'summary_embedding', 'themes']
Node 2 properties: ['document_metadata', 'entities', 'page_content', 'summary', 'summary_embedding', 'themes']
Node 3 properties: ['document_metadata', 'entities', 'page_content', 'summary', 'summary_embedding', 'themes']

### Save and Reload the Graph

Generated artifacts go in the ignored <code>artifacts/</code> folder so running
the notebook does not add large, machine-generated files to the assignment diff.

In [36]:
artifacts_dir = Path("artifacts")
artifacts_dir.mkdir(exist_ok=True)

knowledge_graph_path = artifacts_dir / "cat_health_knowledge_graph.json"
knowledge_graph.save(str(knowledge_graph_path))

loaded_knowledge_graph = KnowledgeGraph.load(str(knowledge_graph_path))

print(f"Saved graph to {knowledge_graph_path}")
print(loaded_knowledge_graph)

Saved graph to artifacts/cat_health_knowledge_graph.json
KnowledgeGraph(nodes: 20, relationships: 51)

#### Question #1

What information did the Ragas graph transforms add beyond the original text,
and why are the two relationship types important for multi-hop questions?

##### Answer

Initially, the graph only contained raw chunk text with no additional knowledge.After the transforms ran, RAGAS enriched the graph with information as below:

1. Summary: This was generated by Summary Extractor. This transform does following:
    a. Compresses long text into key ideas
    b. Makes topic identification easier.
    c. Helps downstream question generation focus on important concepts
2. summary_embedding: This must have been generated by taking the summary and passing it through the embedding model.
3. Themes: Themes are high-level topics extracted from the chunk. Here is the sample from first chunk:
    "themes": [
          "Feline life stages",
          "Preventive healthcare",
          "Individualized risk assessment",
          "Lifetime healthcare management",
          "Clinical guidelines",
          "Veterinary practice",
          "Cat wellness and longevity",
          "Early detection of illness and pain",
          "Owner perceptions of cat healthcare",
          "Underserved feline care",
          "Age-associated treatment pathways"
        ],
4. Entities: This was generated by entity extraction transforms.This transform does following:
    a. Creates semantic anchors in the graph.
    b. Allows RAGAS to connect chunks discussing the same concepts.


why are the two relationship types important for multi-hop questions?

Two relationship in the notebook are Summary_embeddingas and themes.

1. Theme based releationship: Two chunks with simlar themes or topics share a relationship and could be useful for multi-hop questions.

2. Embedding-based relationships: Based on vector similarity of summaries.

They are the mechanism RAGAS uses to create semantic relationships between chunks, and those relationships are what enable realistic multi-hop synthetic evaluation questions.

## Task 4: Inspect the Query Distribution

Ragas can synthesize several kinds of questions:

| Query type | What it tests |
|---|---|
| Single-hop specific | Retrieve one concrete fact or recommendation from one context |
| Multi-hop specific | Combine concrete details from multiple related contexts |
| Multi-hop abstract | Connect broader themes or concepts across contexts |

The distribution is part of the evaluation specification. It determines which
behaviors are common in the generated dataset.

In [37]:
#Given my knowledge graph, what mix of question types should I generate?

query_distribution = default_query_distribution(
    generator_llm,
    kg=loaded_knowledge_graph,
)

print("Available query synthesizers:")
for synthesizer, weight in query_distribution:
    print(f"- {synthesizer.name}: {weight:.0%}")

distribution_total = sum(weight for _, weight in query_distribution)
print(f"Distribution total: {distribution_total:.2f}")

Available query synthesizers:
- single_hop_specific_query_synthesizer: 33%
- multi_hop_abstract_query_synthesizer: 33%
- multi_hop_specific_query_synthesizer: 33%
Distribution total: 1.00

### Define a Custom Distribution

The default is a sensible starting point, but the mix should reflect the
application behavior you care about. This example emphasizes concrete
single-hop questions while preserving coverage of both multi-hop styles.

Adjust the weights below and assign
<code>query_distribution = custom_query_distribution</code> before Task 5 if
you want the generated dataset to use your mix. We define the distribution here
without generating a second test set, which keeps the worked notebook's cost
bounded.

The default helper filters out synthesizers that the enriched graph cannot
support. If a custom multi-hop run reports that no matching relationships exist,
inspect the graph and use only the synthesizers listed by the default distribution.

In [38]:
custom_query_distribution = [
    (
        SingleHopSpecificQuerySynthesizer(llm=generator_llm),
        0.50,
    ),
    (
        MultiHopSpecificQuerySynthesizer(llm=generator_llm),
        0.30,
    ),
    (
        MultiHopAbstractQuerySynthesizer(llm=generator_llm),
        0.20,
    ),
]

assert abs(
    sum(weight for _, weight in custom_query_distribution) - 1.0
) < 1e-9

for synthesizer, weight in custom_query_distribution:
    print(f"- {synthesizer.name}: {weight:.0%}")

- single_hop_specific_query_synthesizer: 50%
- multi_hop_specific_query_synthesizer: 30%
- multi_hop_abstract_query_synthesizer: 20%

#### Question #2

Describe the three query types in your own words. Which type do you expect to be
hardest for a basic dense-retrieval RAG application, and why?

##### Answer

1. Single-Hop Specific

A question whose answer can be found in a single chunk or document section. The RAG system mainly needs to retrieve the correct passage and extract the relevant fact.

Example:

"How often should cats receive rabies vaccinations?"

The answer exists directly in one chunk.

Tests:

Retrieval accuracy
Basic answer extraction

2. Multi-Hop Specific

A question that requires combining multiple concrete facts from different chunks.

Example:

"Why should cats with kidney disease have their hydration monitored?"

One chunk may discuss kidney disease, while another explains the benefits of hydration monitoring. The system must retrieve both and combine them.

Tests:

Retrieval of multiple relevant chunks
Fact synthesis across sources

3. Multi-Hop Abstract

A question that requires connecting broader concepts, themes, or ideas across multiple contexts. The answer is often not explicitly stated anywhere.

Example:

"How do preventive healthcare practices contribute to long-term feline health?"

The answer requires combining ideas from vaccination, nutrition, wellness exams, and disease prevention sections.

Tests:

Retrieval
Cross-document reasoning
Conceptual synthesis
Answer generation quality

Multi-Hop Abstract is usually the hardest because the system must retrieve several conceptually related chunks that may not share the same keywords or embeddings as the question.

## Task 5: Generate and Inspect a Synthetic Test Set

Each generated row contains:

- <code>user_input</code>: the synthetic question
- <code>reference_contexts</code>: source context selected by the generator
- <code>reference</code>: a generated reference answer
- <code>synthesizer_name</code>: the query strategy that produced the row

The reference is generated from selected source context. It is useful, but it
still needs review for accuracy, clarity, safety, and usefulness.

In [39]:
testset_generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings,
    knowledge_graph=loaded_knowledge_graph,
)

synthetic_testset = testset_generator.generate(
    testset_size=TESTSET_SIZE,
    query_distribution=query_distribution,
    run_config=ragas_run_config,
)

testset_df = synthetic_testset.to_pandas()

display(
    testset_df[
        [
            "user_input",
            "reference",
            "synthesizer_name",
        ]
    ]
)

Generating personas: 100%|██████████| 3/3 [00:03<00:00,  1.19s/it]
Generating Scenarios: 100%|██████████| 3/3 [00:14<00:00,  4.74s/it]
Generating Samples: 100%|██████████| 6/6 [00:12<00:00,  2.04s/it]

,user_input,reference,synthesizer_name
0,What does the 2021 AAHA/AAFP Feline Life Stage...,The guidelines update and extend the 2010 AAFP...,single_hop_specific_query_synthesizer
1,What does AAHA stand for in the feline life st...,AAHA appears in the 2021 AAHA/AAFP Feline Life...,single_hop_specific_query_synthesizer
2,"How do ""environmental enrichment"" and ""client ...",Environmental enrichment is described as essen...,multi_hop_abstract_query_synthesizer
3,"How do the themes ""Obesity prevention"" and ""Ne...","Obesity prevention starts with kittens, and ne...",multi_hop_abstract_query_synthesizer
4,According to the JAAHA.ORG feline life stage g...,The guidelines state that the initial veterina...,multi_hop_specific_query_synthesizer
5,How should chronic kidney disease change a sen...,"For mature adult cats, the minimum protein all...",multi_hop_specific_query_synthesizer

In [40]:
testset_path = artifacts_dir / "cat_health_synthetic_testset.jsonl"
testset_df.to_json(
    testset_path,
    orient="records",
    lines=True,
    force_ascii=False,
)

print("Examples by synthesizer:")
print(testset_df["synthesizer_name"].value_counts())
print()
print(f"Saved candidate examples to {testset_path}")

Examples by synthesizer:
synthesizer_name
single_hop_specific_query_synthesizer    2
multi_hop_abstract_query_synthesizer     2
multi_hop_specific_query_synthesizer     2
Name: count, dtype: int64

Saved candidate examples to artifacts/cat_health_synthetic_testset.jsonl

### Abstracted Ragas Alternative

The graph-first path above makes each Ragas stage inspectable and lets you save
the enriched graph before generation. Ragas also provides a one-call helper for
content that is already chunked:

~~~python
quick_generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings,
)
quick_testset = quick_generator.generate_with_chunks(
    chunks=generation_chunks,
    testset_size=TESTSET_SIZE,
    transforms=transforms,
    run_config=ragas_run_config,
)
~~~

This alternative is shown rather than executed so the notebook does not repeat
the same billable graph enrichment and test-set generation.

#### Question #3

What are the tradeoffs between the unrolled and one-call Ragas generation paths?
When would you choose each one?

##### Answer

The one-call path prioritizes simplicity and speed by hiding graph creation, enrichment, and question generation behind a single API call. The unrolled path exposes each stage of the pipeline, providing better observability, debugging, validation, and customization at the cost of additional complexity. I would use the one-call path for rapid prototyping and the unrolled path for production evaluation systems where I need control over data quality and generation behavior.

|Aspect|One-call|Unrolled path|
| -- | -- | -- |
|Simplicity| very simple with few lines of code | More setup and code|
|Visibility | Internal steps are hidden | Full visibility into every stage|
|Customization | Limited | Highly customizable|
|Validation | Limited | Highly customizable |
|Production readiness | Good for prototypes | Better for production-grade evaluation pipelines|

## Activity #1: Review and Curate the Dataset

Review every generated row before uploading it.

For each example, check:

1. Is the question answerable from the reference contexts?
2. Is the reference answer fully supported by those contexts?
3. Is the wording natural for a plausible user?
4. Does the example duplicate another row?
5. Does it preserve the corpus's medical-safety boundaries?

Requirements:

- Remove or repair at least one weak example, if one exists.
- Record why you kept, edited, or removed it.
- Keep the synthesizer name in metadata so you can diagnose query-type failures.

In [45]:
# loop thorugh all rows of testset_df , display the user_input, reference and reference_contexts
for index, row in testset_df.iterrows():
    print(f"User Input: {row['user_input']}")
    print(f"Reference: {row['reference']}")
    print(f"Reference Contexts: {row['reference_contexts']}")
    print("\n")

User Input: What does the 2021 AAHA/AAFP Feline Life Stage Guidelines say about the cat life stage grouping?
Reference: The guidelines update and extend the 2010 AAFP–AAHA Feline Life Stage Guidelines, and they divide the cat\"s life span into a five-stage grouping with four distinct age-related stages: kitten, young adult, mature adult, and senior, plus an end-of-life stage, instead of the previous six.
Reference Contexts: ['VETERINARY PRACTICE GUIDELINES\n2021 AAHA/AAFP Feline Life Stage Guidelines*\nJessica Quimby, DVM, PhD, DACVIM y, Shannon Gowland, DVM, DABVP y, Hazel C. Carney, DVM, MS, DABVP,\nTheresa DePorter, DVM, MRCVS, DACVB, DECAWBM, Paula Plummer, LVT, VTS (ECC, SAIM), Jodi Westropp,\nDVM, PhD, DACVIM\nABSTRACT\nThe guidelines, authored by a Task Force ofexperts in feline clinical medicine, are an update and extension of the AAFP–AAHA\nFeline Life Stage Guidelines published in 2010. The guidelines are published simultaneously in theJournal of Feline Medicine and\nSurgery(volume 23, issue 3, pages 211–233, DOI: 10.1177/1098612X21993657) and theJournal of the American Animal Hospital\nAssociation(volume 57, issue 2, pages 51–72, DOI: 10.5326/JAAHA-MS-7189). A noteworthy change from the earlier guidelines is\nthe division of the cat’sl i f e s p a ni n t oaﬁve-stage grouping with four distinct age-related stages (kitten, young adult, mature adult,\nand senior) as well as an end-of-life stage, instead of the previous six. This simpliﬁed grouping is consistent with how pet owners\ngenerally perceive their cat’s maturation and aging process, and provides a readily understood basis for an evolving, individualized,\nlifelong feline healthcare strategy. The guidelines include a comprehensive table on the components of a feline wellness visit that\nprovides a framework for systematically implementing an individualized life stage approach to fe line healthcare. Included are\nrecommendations for managing the most critical health-related factors in relation to a cat’s life stage. These recommendations are\nfurther explained in the followi ng categories: behavior and envir onmental needs; elimination; life stage nutrition and weight\nmanagement; oral health; parasite control; vaccination; zoonoses and human safety; and recommended diagnostics based on\nlife stage. A discussion on overcoming barriers to veterinary v i s i t sb yc a to w n e r so f f e r sp r a ctical advice on one of the most\nchallenging aspects of delivering regular feline healthcare.(JA mA n i mH o s pA s s o c2021; 57:51–72. DOI 10.5326/JAAHA-MS-7189)\nAFFILIATIONS\nThe Ohio State University, Department of V eterinary Clinical Sciences, Co-\nlumbus, Ohio, USA (J.Q.); OVC Smith Lane Animal Hospital, Ontario V et-\nerinary College, Guelph, Ontario, Canada (S.G.); WestV et Emergency and\nSpecialty Center, Garden City, Idaho, USA (H.C.C.); Oakland V eterinary\nReferral Services, Bloom ﬁeld Hills, Michigan, USA (T.D.); T exas A&M Uni-\nversity V eterinary Medical T eaching Hospital, College Station, T exas, USA\n(P .P .); and University of California, Davis, School of V eterinary Medicine,\nDavis, California, USA (J.W.).\nKEYWORDS\nFeline life stage; kitten; adult; senior; veterinary; healthcare examination;\nmedical history; behavior; risk assessment; elimination\nCorrespondence: quimby.19@osu.edu (J.Q.)\n* Boehringer Ingelheim Animal Health USA Inc., CareCredit, Dechra Vet-\nerinary Products, IDEXX Laboratories, Inc., Merck Animal Health, and Zoetis\nPetcare supported the development of the 2021 AAHA/AAFP Feline Life\nStage Guidelinesand resources through an educational grant to AAHA.\n† J. Quimby and S. Gowland were cochairs of the 2021 AAHA/AAFP\nFeline Life Stage Guidelines Task Force.\nThese guidelines were prepared by a Task Force of experts convened\nby the American Animal Hospital Association (AAHA) and the American\nAssociation of Feline Practitioners (AAFP) and were subjected to a for-\nmal peer-review process. This document is intended as a guideline only,\nnot an AAHA or AAFP standard of care. These guidelines and recom-\nmendations should not be construed as dictating an exclusive protocol,\ncourse of treatment, or procedure. Variations in practice may be war-\nranted based on the needs of the individual patient, resources, and\nlimitations unique to each individual practice setting. Evidence-based\nsupport for speciﬁc recommendations has been cited whenever pos-\nsible and appropriate.\nOther recommendations are based on practical clinical experience and\na consensus of expert opinion. Further research is needed to document\nsome of these recommendations. Because each case is different, vet-\nerinarians must base their decisions on the best available scientiﬁc ev-\nidence in conjunction with their own knowledge and experience.\nBCS (body condition score); DER (daily energy requirements); DJD\n(degenerative joint disease); FCV (feline calicivirus); FeLV (feline leukemia\nvirus); FHV-1 (feline herpesvirus type 1); FIC (feline idiopathic cystitis);\nFPV (feline panleukopenia virus); GI (gastrointestinal); HARD (heartworm-\nassociated respiratory disease); MCS (muscle condition score); RER\n(resting energy requirements); T4 (thyroxine)\nAccepted for publication: October 4, 2020.\nª 2021 by American Animal Hospital Association, American Association of Feline Practitioners, and International Society of Feline Medicine JAAHA.ORG 51']


User Input: What does AAHA stand for in the feline life stage guidelines?
Reference: AAHA appears in the 2021 AAHA/AAFP Feline Life Stage Guidelines, which provide a comprehensive age-associated framework for promoting health and longevity throughout a cat’s lifetime. The guidelines were developed by a Task Force of experts in feline clinical medicine and are intended to guide individualized risk assessment, preventive healthcare strategies, and treatment pathways as the cat matures.
Reference Contexts: ['Introduction\nThe feline patient ’s life stage is the most fundamental presentation\nfactor the practitioner encounters in a regular examination visit.\nMost of the components of a treatment or healthcare plan are\nguided by the patient ’s life stage, progressing from kitten to young\nadult, mature adult, and senior and concluding with the end-of-life\nstage. Because a cat can transition from one life stage to another in a\nshort period of time, each examination visit should include a life\nstage assessment. The 2021 AAHA/AAFP Feline Life Stage Guidelines\nprovide a comprehensive age-associated framework for promoting\nhealth and longevity throughout a cat ’s lifetime. The guidelines were\ndeveloped by a T ask Force of experts in feline clinical medicine.\nTheir recommendations are a practical resource to guide individu-\nalized risk assessment, preventive healthcare strategies, and treat-\nment pathways that evolve as the cat matures.\nAn evidence-guided framework for managing a cat ’s healthcare\nthroughout its lifetime has never been more important in feline\npractice than it is now. Cats are the most popular pet in the United\nStates.\n1 A great anomaly in feline practice is that although most\nowners consider their cats to be family members, cats are sub-\nstantially underserved in the primary care setting compared with\ndogs.\n2 In 2006, owners took their dogs to veterinarians more than\ntwice as often as cats: 2.3 times/year for dogs versus 1.1 times/year\nfor cats.\n3 This healthcare use imbalance persists to the present day.\nCat owners often express a belief that their pets “do not need\nmedical care.” Two reasons for this misconception are that signs of\nillness and pain are often dif ﬁcult to detect in the sometimes re-\nclusive or stoic cat, and that cats are perceived to be self-suf ﬁcient.\nSpeciﬁc objectives of the guidelines are (1) to de ﬁne distinct\nfeline life stages consistent with how pet owners generally perceive\nTABLE 1\nFeline Life Stages\nª Voren1/iStock, spxChrome/E+, AaronAmat/iStock, AngiePhotos/iStock via Getty Images Plus\n52 JAAHA | 57:2 Mar/Apr 2021']


User Input: How do "environmental enrichment" and "client education" support lifelong feline care, especially for cats showing pain or anxiety?
Reference: Environmental enrichment is described as essential for maintaining the mental and physical well-being of cats, because an indoor-only lifestyle can increase the risks of compromised welfare, illness, obesity, and behavior problems due to environmental limitations. The ideal feline home environment should provide plentiful, thoughtfully distributed resources, including resting areas, feeding stations, water sources, scratching posts, and litter boxes, along with appealing places for resting and hiding. Client education is also a key responsibility for all staff members, and every life stage has specific items to discuss during veterinary visits. The practice team can improve compliance by helping owners understand that they are an integral part of the healthcare team, and by using open-ended questions and educational handouts or online resources to gather detailed histories and explain an individualized, lifelong healthcare strategy. This matters especially when evaluating cats for pain or anxiety, since signs can be subtle and owners may need guidance to notice changes in behavior, environment, or daily habits.

In [48]:
# Activity #1 workspace
#
# Start with every generated example. Replace this with your reviewed subset.
approved_testset_df = testset_df.copy()
review_status = "review_required"

# Examples:
approved_testset_df.loc[1, "user_input"] = "What do the 2021 AAHA/AAFP Feline Life Stage Guidelines provide for feline healthcare?"
approved_testset_df.loc[1, "reference"] = (
    "The 2021 AAHA/AAFP Feline Life Stage Guidelines provide "
    "a comprehensive age-associated framework for promoting health and longevity throughout a cat's lifetime. "
    "The guidelines were developed by a Task Force of experts in feline clinical medicine and are intended "
    "to guide individualized risk assessment, preventive healthcare strategies, and treatment pathways as the cat matures."
)

review_status = "student_reviewed"

display(
    approved_testset_df[
        [
            "user_input",
            "reference_contexts",
            "reference",
            "synthesizer_name",
        ]
    ]
)

,user_input,reference_contexts,reference,synthesizer_name
0,What does the 2021 AAHA/AAFP Feline Life Stage...,[VETERINARY PRACTICE GUIDELINES\n2021 AAHA/AAF...,The guidelines update and extend the 2010 AAFP...,single_hop_specific_query_synthesizer
1,What do the 2021 AAHA/AAFP Feline Life Stage G...,[Introduction\nThe feline patient ’s life stag...,The 2021 AAHA/AAFP Feline Life Stage Guideline...,single_hop_specific_query_synthesizer
2,"How do ""environmental enrichment"" and ""client ...",[<1-hop>\n\nDetecting signs of pain or anxiety...,Environmental enrichment is described as essen...,multi_hop_abstract_query_synthesizer
3,"How do the themes ""Obesity prevention"" and ""Ne...","[<1-hop>\n\n10 months, primarily by phone cont...","Obesity prevention starts with kittens, and ne...",multi_hop_abstract_query_synthesizer
4,According to the JAAHA.ORG feline life stage g...,[<1-hop>\n\nthan observed or learned. 44 Impor...,The guidelines state that the initial veterina...,multi_hop_specific_query_synthesizer
5,How should chronic kidney disease change a sen...,[<1-hop>\n\ngood starting point is to calculat...,"For mature adult cats, the minimum protein all...",multi_hop_specific_query_synthesizer

### Activity #1 Notes

- Example reviewed: Row 2 — "What does AAHA stand for in the feline life stage guidelines?"
- Decision: Edited
- Reason: The question and reference answer were not fully aligned. The question asks for the meaning of "AAHA," while the reference answer describes the purpose of the 2021 AAHA/AAFP Feline Life Stage Guidelines rather than defining the acronym.
- Any safety or grounding issue found:No medical-safety issue was found. The issue was a grounding/alignment problem because the reference answer did not directly answer the generated question.

---
# Breakout Room #2
## RAG Evaluation with LangSmith

We will upload the reviewed examples, build one RAG application, and evaluate two
retrieval settings against the same dataset and judges.

Keeping the dataset and evaluators fixed makes the application change easier to
interpret.

## Task 6: Create a LangSmith Dataset

The dataset stores the question as input and the reviewed synthetic answer plus
reference contexts as outputs. Query type and provenance remain metadata.

A unique suffix prevents accidental duplication when the whole notebook is rerun.
For a long-lived team dataset, use a stable name and manage versions deliberately.

In [ ]:
def as_string_list(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value]
    if hasattr(value, "tolist"):
        converted = value.tolist()
        if isinstance(converted, list):
            return [str(item) for item in converted]
    return [str(value)]


if review_status != "student_reviewed":
    raise ValueError(
        "Complete Activity #1, curate approved_testset_df, and set "
        "review_status = 'student_reviewed' before uploading."
    )


langsmith_client = Client()
dataset_name = (
    "aim-session-5-cat-health-synthetic-"
    f"{uuid4().hex[:8]}"
)

langsmith_dataset = langsmith_client.create_dataset(
    dataset_name=dataset_name,
    description=(
        "Ragas-generated questions for the AI Makerspace "
        "cat health RAG lesson."
    ),
    metadata={
        "session": 5,
        "source": "ragas",
        "corpus": str(corpus_path),
    },
)

langsmith_examples = []
for _, row in approved_testset_df.iterrows():
    langsmith_examples.append(
        {
            "inputs": {
                "question": str(row["user_input"]),
            },
            "outputs": {
                "answer": str(row["reference"]),
                "reference_contexts": as_string_list(
                    row["reference_contexts"]
                ),
            },
            "metadata": {
                "synthesizer_name": str(row["synthesizer_name"]),
                "synthetic_reference": True,
                "review_status": review_status,
            },
        }
    )

langsmith_client.create_examples(
    dataset_id=langsmith_dataset.id,
    examples=langsmith_examples,
)

print(f"Created dataset: {dataset_name}")
print(f"Examples uploaded: {len(langsmith_examples)}")

#### Question #4

Why is it useful to keep <code>synthesizer_name</code>,
<code>synthetic_reference</code>, and review status as metadata instead of
discarding them after upload?

##### Answer

Your answer here.

## Task 7: Build a Baseline RAG Application

The baseline uses the same PDF corpus, recursive character chunks, embeddings
and chat generation through Vercel AI Gateway, in-memory Qdrant, and a
context-only answer prompt.

The target returns both the answer and the retrieved contexts. Returning
intermediate retrieval output makes it possible to evaluate retrieval relevance
and answer groundedness without reconstructing hidden steps.

In [ ]:
rag_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=75,
)
rag_documents = rag_splitter.split_documents(source_documents)

rag_embeddings = OpenAIEmbeddings(
    model=EMBEDDING_MODEL_NAME,
    api_key=gateway_api_key,
    base_url=GATEWAY_BASE_URL,
    check_embedding_ctx_length=False,
)
vector_store = QdrantVectorStore.from_documents(
    documents=rag_documents,
    embedding=rag_embeddings,
    location=":memory:",
    collection_name=f"cat_health_eval_{uuid4().hex[:8]}",
)

print(f"Source PDF pages: {len(source_documents)}")
print(f"RAG chunks: {len(rag_documents)}")

In [ ]:
RAG_SYSTEM_PROMPT = """You are an educational cat health assistant.

Answer the question using only the retrieved context.
If the context is insufficient, say that the corpus does not provide enough
information.

Do not diagnose, prescribe treatment, or present the response as a substitute
for a veterinarian. Clearly preserve any urgent-care guidance found in the
context.

Retrieved context:
{context}
"""

rag_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", RAG_SYSTEM_PROMPT),
        ("human", "{question}"),
    ]
)
rag_llm = ChatOpenAI(
    model=RAG_MODEL_NAME,
    api_key=gateway_api_key,
    base_url=GATEWAY_BASE_URL,
)
answer_chain = rag_prompt | rag_llm | StrOutputParser()

In [ ]:
def format_retrieved_document(document) -> str:
    page_number = document.metadata.get("page_number", "unknown")
    source = document.metadata.get("source", "course corpus")
    return (
        f"Page: {page_number}\n"
        f"Source: {source}\n"
        f"{document.page_content}"
    )


def make_rag_target(retrieval_k: int):
    retriever = vector_store.as_retriever(
        search_kwargs={"k": retrieval_k}
    )

    def target(inputs: dict) -> dict:
        question = inputs["question"]
        retrieved_documents = retriever.invoke(question)
        contexts = [
            format_retrieved_document(document)
            for document in retrieved_documents
        ]
        answer = answer_chain.invoke(
            {
                "question": question,
                "context": "\n\n".join(contexts),
            }
        )
        return {
            "answer": answer,
            "contexts": contexts,
            "retrieval_k": retrieval_k,
        }

    target.__name__ = f"cat_health_rag_k_{retrieval_k}"
    return target

In [ ]:
baseline_retrieval_k = 3
baseline_target = make_rag_target(baseline_retrieval_k)

spot_check_question = (
    "What components should be considered during a feline wellness visit?"
)
baseline_spot_check = baseline_target(
    {"question": spot_check_question}
)

print(baseline_spot_check["answer"])
print()
print("Retrieved contexts:")
for context in baseline_spot_check["contexts"]:
    print("---")
    print(context[:700])

## Task 8: Define RAG Evaluators

We will evaluate three different relationships:

| Metric | Comparison |
|---|---|
| Answer correctness | Generated answer vs reviewed reference answer |
| Answer groundedness | Generated answer vs contexts retrieved during that run |
| Retrieval relevance | Retrieved contexts vs input question |

These can disagree. A fluent answer can be correct but unsupported by its retrieved
context, or well grounded in context that does not answer the question.

OpenEvals provides reusable prompts, while the small wrapper functions map our
application's dictionary keys into those prompts.

In [ ]:
gateway_judge_llm = ChatOpenAI(
    model=JUDGE_MODEL_NAME,
    api_key=gateway_api_key,
    base_url=GATEWAY_BASE_URL,
)

correctness_judge = create_llm_as_judge(
    prompt=CORRECTNESS_PROMPT,
    feedback_key="answer_correctness",
    judge=gateway_judge_llm,
    continuous=True,
)
groundedness_judge = create_llm_as_judge(
    prompt=RAG_GROUNDEDNESS_PROMPT,
    feedback_key="answer_groundedness",
    judge=gateway_judge_llm,
    continuous=True,
)
retrieval_relevance_judge = create_llm_as_judge(
    prompt=RAG_RETRIEVAL_RELEVANCE_PROMPT,
    feedback_key="retrieval_relevance",
    judge=gateway_judge_llm,
    continuous=True,
)

In [ ]:
def answer_correctness(
    inputs: dict,
    outputs: dict,
    reference_outputs: dict,
) -> dict:
    return correctness_judge(
        inputs=inputs["question"],
        outputs=outputs["answer"],
        reference_outputs=reference_outputs["answer"],
    )


def answer_groundedness(
    outputs: dict,
) -> dict:
    return groundedness_judge(
        context=outputs["contexts"],
        outputs=outputs["answer"],
    )


def retrieval_relevance(
    inputs: dict,
    outputs: dict,
) -> dict:
    return retrieval_relevance_judge(
        inputs=inputs["question"],
        context=outputs["contexts"],
    )


rag_evaluators = [
    answer_correctness,
    answer_groundedness,
    retrieval_relevance,
]

#### Question #5

Give one example where answer correctness and groundedness could disagree. What
would that disagreement tell you to inspect in the trace?

##### Answer

Your answer here.

## Task 9: Run the Baseline Experiment

LangSmith runs the target once for each dataset example, applies all evaluators,
and groups the traces under one experiment.

After the run, open the experiment URL and inspect individual failures. Aggregate
scores alone do not explain whether the problem came from the generated dataset,
retrieval, prompting, or the judge.

In [ ]:
baseline_results = evaluate(
    baseline_target,
    data=dataset_name,
    evaluators=rag_evaluators,
    experiment_prefix="cat-health-rag-baseline-k3",
    description=(
        "Baseline cat health RAG with 500-character chunks "
        "and retrieval k=3."
    ),
    metadata={
        "chunk_size": 500,
        "chunk_overlap": 75,
        "retrieval_k": baseline_retrieval_k,
        "embedding_model": EMBEDDING_MODEL_NAME,
        "rag_model": RAG_MODEL_NAME,
        "judge_model": JUDGE_MODEL_NAME,
        "ai_gateway_base_url": GATEWAY_BASE_URL,
    },
    max_concurrency=MAX_CONCURRENCY,
)

print(f"Baseline experiment: {baseline_results.experiment_name}")

### Baseline Inspection Notes

- Lowest-scoring example:
- Metric that failed:
- Was the synthetic reference valid?
- Was the retrieved context relevant and sufficient?
- Did the answer add unsupported information?

## Task 10: Change One Retrieval Variable and Re-Evaluate

The source notebook changed chunk size, embedding model, retriever settings, and
prompt style at the same time. That makes any score change hard to explain.

Here we change only retrieval depth:

~~~text
baseline:  k = 3
candidate: k = 6
~~~

The chunks, embeddings, vector store, answer model, prompt, dataset, and evaluators
remain fixed.

In [ ]:
candidate_retrieval_k = 6
candidate_target = make_rag_target(candidate_retrieval_k)

candidate_spot_check = candidate_target(
    {"question": spot_check_question}
)

print(candidate_spot_check["answer"])
print()
print(
    "Retrieved context count:",
    len(candidate_spot_check["contexts"]),
)

In [ ]:
candidate_results = evaluate(
    candidate_target,
    data=dataset_name,
    evaluators=rag_evaluators,
    experiment_prefix="cat-health-rag-candidate-k6",
    description=(
        "Candidate cat health RAG with the same index and "
        "retrieval k increased from 3 to 6."
    ),
    metadata={
        "chunk_size": 500,
        "chunk_overlap": 75,
        "retrieval_k": candidate_retrieval_k,
        "embedding_model": EMBEDDING_MODEL_NAME,
        "rag_model": RAG_MODEL_NAME,
        "judge_model": JUDGE_MODEL_NAME,
        "ai_gateway_base_url": GATEWAY_BASE_URL,
        "changed_variable": "retrieval_k",
    },
    max_concurrency=MAX_CONCURRENCY,
)

print(f"Candidate experiment: {candidate_results.experiment_name}")

#### Question #6

Why is changing one variable at a time useful? If correctness improves while
retrieval relevance falls, what might the larger value of <code>k</code> be doing?

##### Answer

Your answer here.

## Activity #2: Compare, Diagnose, and Iterate

Compare the baseline and candidate experiments in LangSmith.

Requirements:

1. Record the mean score for each evaluator in both experiments.
2. Inspect at least two examples whose scores changed.
3. Decide whether <code>k=6</code> improved the application overall.
4. Choose one new variable to test: chunk size, chunk overlap, embedding model,
   prompt, or retrieval depth.
5. State your prediction before running the experiment.
6. Run a third experiment and explain the result.

Keep the reviewed dataset and evaluators fixed. If you discover that an example
itself is invalid, fix or remove the example and treat that as dataset maintenance,
not an application improvement.

In [ ]:
# Activity #2 workspace
#
# A retrieval-depth experiment can reuse the existing vector store:
# student_retrieval_k = 4
# student_target = make_rag_target(student_retrieval_k)
#
# If you change chunking or the embedding model, build a new vector store,
# then create a target with the same output contract:
# {
#     "answer": str,
#     "contexts": list[str],
#     "retrieval_k": int,
# }
#
# Run evaluate(...) with a descriptive experiment_prefix and metadata that
# records exactly what changed.

### Activity #2 Notes

- Variable changed:
- Prediction:
- Baseline result:
- Candidate result:
- Third experiment result:
- Two traces inspected:
- Decision:
- Cost or latency tradeoff:

## Advanced Build: Add Robustness and Adversarial Cases

Synthetic data can cover failure modes as well as happy-path questions.

Add at least three reviewed cases such as:

- A user asks for a diagnosis or medication dose that the corpus cannot support.
- A prompt-injection attempt asks the assistant to ignore its context-only policy.
- An unrelated question should trigger an insufficient-context response.
- Retrieved text contains a malicious instruction that should be treated as data,
  not as an instruction.

For each case, define the expected behavior and an evaluator that measures it.
Track normal-task performance and attack resistance separately so a system does
not appear safe merely because it refuses everything.

## Final Takeaways

- Synthetic data is a starting point for evaluation, not a replacement for human
  review or production examples.
- The knowledge graph and query distribution shape which capabilities the dataset
  measures.
- Store provenance and review metadata so failures can be traced back to the data.
- Return retrieval output from the target when retrieval and grounding matter.
- Evaluate retrieval, grounding, and answer quality separately.
- Change one application variable at a time when you want an interpretable result.