# RAGAS evaluation with cost analysis

This notebook evaluates open-source Fireworks AI powered RAG app against an OpenAI gpt-4.1-mini powered equivalent. It compares cost via LangSmith

# Environment Setup

In [1]:
from eval.generate_testset import generate_testset
from eval.runner import run_rag_over_testset
from app.rag import get_rag_graph
import os, pandas as pd
from dotenv import load_dotenv
from langsmith import tracing_context
from eval.ragas_scoring import score_rag_rows_sync, summarize_scores, compare_providers

load_dotenv()

os.environ["LANGSMITH_PROJECT"] = os.environ["LANGSMITH_PROJECT_FIREWORKS"]
os.environ["LANGSMITH_TRACING"] = "true"

# Generate or Load Test Set

Generate Test set with RAGAS

In [2]:
testset_df = generate_testset(data_dir="data", test_size=3)

# Display test set
testset_df

Applying SummaryExtractor:   0%|          | 0/40 [00:00<?, ?it/s]

Applying EmbeddingExtractor:   0%|          | 0/40 [00:00<?, ?it/s]

/Users/saurabh3981/Desktop/agenticai/code/AIEC1/10_LLM_Servers/.venv/lib/python3.13/site-packages/ragas/testset/transforms/base.py:198: UserWarning: Using sync embedding model OpenAIEmbeddings in async context. This may impact performance. Consider using an async-compatible embedding model for better performance.
  property_name, property_value = await self.extract(node)

Applying ThemesExtractor:   0%|          | 0/40 [00:00<?, ?it/s]

Applying NERExtractor:   0%|          | 0/40 [00:00<?, ?it/s]

Applying CosineSimilarityBuilder:   0%|          | 0/1 [00:00<?, ?it/s]

Applying OverlapScoreBuilder:   0%|          | 0/1 [00:00<?, ?it/s]

Generating personas:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/3 [00:00<?, ?it/s]

,user_input,reference,reference_contexts
0,Who is Paula Plummer in the 2021 AAHA/AAFP Fel...,"Paula Plummer, LVT, VTS (ECC, SAIM), is one of...",[VETERINARY PRACTICE GUIDELINES\n2021 AAHA/AAF...
1,how feline retrovirus testing and management l...,The 2020 AAFP feline retrovirus testing and ma...,[<1-hop>\n\nguidelines. J Feline Med Surg 2019...
2,What are the recommended litter box management...,"For kittens, it is recommended to discuss appr...",[<1-hop>\n\nassume these behaviors are normal ...

# Run Fireworks RAG Pipeline (with LangSmith)

In [3]:
with tracing_context(project_name=os.environ["LANGSMITH_PROJECT_FIREWORKS"]):
    firework_graph = get_rag_graph("fireworks")
    firework_eval_result = run_rag_over_testset(firework_graph, testset_df)


firework_eval_result[0]

{'user_input': 'Who is Paula Plummer in the 2021 AAHA/AAFP Feline Life Stage Guidelines?',
 'reference': 'Paula Plummer, LVT, VTS (ECC, SAIM), is one of the authors of the 2021 AAHA/AAFP Feline Life Stage Guidelines and is affiliated with the Texas A&M University Veterinary Medical Teaching Hospital, College Station, Texas, USA.',
 'reference_contexts': ['VETERINARY PRACTICE GUIDELINES\n2021 AAHA/AAFP Feline Life Stage Guidelines*\nJessica Quimby, DVM, PhD, DACVIMy, Shannon Gowland, DVM, DABVPy, Hazel C. Carney, DVM, MS, DABVP,\nTheresa DePorter, DVM, MRCVS, DACVB, DECAWBM, Paula Plummer, LVT, VTS (ECC, SAIM), Jodi Westropp,\nDVM, PhD, DACVIM\nABSTRACT\nThe guidelines, authored by a Task Force of experts in feline clinical medicine, are an update and extension of the AAFP–AAHA\nFeline Life Stage Guidelines published in 2010. The guidelines are published simultaneously in the Journal of Feline Medicine and\nSurgery (volume 23, issue 3, pages 211–233, DOI: 10.1177/1098612X21993657) and the Journal of the American Animal Hospital\nAssociation (volume 57, issue 2, pages 51–72, DOI: 10.5326/JAAHA-MS-7189). A noteworthy change from the earlier guidelines is\nthe division of the cat’s lifespan into a ﬁve-stage grouping with four distinct age-related stages (kitten, young adult, mature adult,\nand senior) as well as an end-of-life stage, instead of the previous six. This simpliﬁed grouping is consistent with how pet owners\ngenerally perceive their cat’s maturation and aging process, and provides a readily understood basis for an evolving, individualized,\nlifelong feline healthcare strategy. The guidelines include a comprehensive table on the components of a feline wellness visit that\nprovides a framework for systematically implementing an individualized life stage approach to feline healthcare. Included are\nrecommendations for managing the most critical health-related factors in relation to a cat’s life stage. These recommendations are\nfurther explained in the following categories: behavior and environmental needs; elimination; life stage nutrition and weight\nmanagement; oral health; parasite control; vaccination; zoonoses and human safety; and recommended diagnostics based on\nlife stage. A discussion on overcoming barriers to veterinary visits by cat owners offers practical advice on one of the most\nchallenging aspects of delivering regular feline healthcare. (J Am Anim Hosp Assoc 2021; 57:51–72. DOI 10.5326/JAAHA-MS-7189)\nAFFILIATIONS\nThe Ohio State University, Department of Veterinary Clinical Sciences, Co-\nlumbus, Ohio, USA (J.Q.); OVC Smith Lane Animal Hospital, Ontario Vet-\nerinary College, Guelph, Ontario, Canada (S.G.); WestVet Emergency and\nSpecialty Center, Garden City, Idaho, USA (H.C.C.); Oakland Veterinary\nReferral Services, Bloomﬁeld Hills, Michigan, USA (T.D.); Texas A&M Uni-\nversity Veterinary Medical Teaching Hospital, College Station, Texas, USA\n(P.P.); and University of California, Davis, School of Veterinary Medicine,\nDavis, California, USA (J.W.).\nKEYWORDS\nFeline life stage; kitten; adult; senior; veterinary; healthcare examination;\nmedical history; behavior; risk assessment; elimination\nCorrespondence: quimby.19@osu.edu (J.Q.)\n* Boehringer Ingelheim Animal Health USA Inc., CareCredit, Dechra Vet-\nerinary Products, IDEXX Laboratories, Inc., Merck Animal Health, and Zoetis\nPetcare supported the development of the 2021 AAHA/AAFP Feline Life\nStage Guidelines and resources through an educational grant to AAHA.\n† J. Quimby and S. Gowland were cochairs of the 2021 AAHA/AAFP\nFeline Life Stage Guidelines Task Force.\nThese guidelines were prepared by a Task Force of experts convened\nby the American Animal Hospital Association (AAHA) and the American\nAssociation of Feline Practitioners (AAFP) and were subjected to a for-\nmal peer-review process. This document is intended as a guideline only,\nnot an AAHA or AAFP standard of care. These guidelines and recom-'],
 'retrieved_contexts': ['TABLE 2 (Continued)\n2021 AAHA/AAFP Feline Life Stage Guidelines\nJAAHA.ORG\n55',
  'VETERINARY PRACTICE GUIDELINES\n2021 AAHA/AAFP Feline Life Stage Guidelines*\nJessica Quimby, DVM, PhD, DACVIMy, Shannon Gowland, DVM, DABVPy, Hazel C. Carney, DVM, MS, DABVP,\nTheresa DePorter, DVM, MRCVS, DACVB, DECAWBM, Paula Plummer, LVT, VTS (ECC, SAIM), Jodi Westropp,\nDVM, PhD, DACVIM\nABSTRACT\nThe guidelines, authored by a Task Force of experts in feline clinical medicine, are an update and extension of the AAFP–AAHA\nFeline Life Stage Guidelines published in 2010. The guidelines are published simultaneously in the Journal of Feline Medicine and\nSurgery (volume 23, issue 3, pages 211–233, DOI: 10.1177/1098612X21993657) and the Journal of the American Animal Hospital\nAssociation (volume 57, issue 2, pages 51–72, DOI: 10.5326/JAAHA-MS-7189). A noteworthy change from the earlier guidelines is\nthe division of the cat’s lifespan into a ﬁve-stage grouping with four distinct age-related stages (kitten, young adult, mature adult,\nand senior) as well as an end-of-life stage, instead of the previous six. This simpliﬁed grouping is consistent with how pet owners\ngenerally perceive their cat’s maturation and aging process, and provides a readily understood basis for an evolving, individualized,\nlifelong feline healthcare strategy. The guidelines include a comprehensive table on the components of a feline wellness visit that\nprovides a framework for systematically implementing an individualized life stage approach to feline healthcare. Included are\nrecommendations for managing the most critical health-related factors in relation to a cat’s life stage. These recommendations are\nfurther explained in the following categories: behavior and environmental needs; elimination; life stage nutrition and weight\nmanagement; oral health; parasite control; vaccination; zoonoses and human safety; and recommended diagnostics based on\nlife stage. A discussion on overcoming barriers to veterinary visits by cat owners offers practical advice on one of the most\nchallenging aspects of delivering regular feline healthcare. (J Am Anim Hosp Assoc 2021; 57:51–72. DOI 10.5326/JAAHA-MS-7189)\nAFFILIATIONS\nThe Ohio State University, Department of Veterinary Clinical Sciences, Co-\nlumbus, Ohio, USA (J.Q.); OVC Smith Lane Animal Hospital, Ontario Vet-\nerinary College, Guelph, Ontario, Canada (S.G.); WestVet Emergency and\nSpecialty Center, Garden City, Idaho, USA (H.C.C.); Oakland Veterinary\nReferral Services, Bloomﬁeld Hills, Michigan, USA (T.D.); Texas A&M Uni-\nversity Veterinary Medical Teaching Hospital, College Station, Texas, USA\n(P.P.); and University of California, Davis, School of Veterinary Medicine,\nDavis, California, USA (J.W.).\nKEYWORDS\nFeline life stage; kitten; adult; senior; veterinary; healthcare examination;\nmedical history; behavior; risk assessment; elimination\nCorrespondence: quimby.19@osu.edu (J.Q.)\n* Boehringer Ingelheim Animal Health USA Inc., CareCredit, Dechra Vet-\nerinary Products, IDEXX Laboratories, Inc., Merck Animal Health, and Zoetis\nPetcare supported the development of the 2021 AAHA/AAFP Feline Life\nStage Guidelines and resources through an educational grant to AAHA.\n† J. Quimby and S. Gowland were cochairs of the 2021 AAHA/AAFP\nFeline Life Stage Guidelines Task Force.\nThese guidelines were prepared by a Task Force of experts convened\nby the American Animal Hospital Association (AAHA) and the American\nAssociation of Feline Practitioners (AAFP) and were subjected to a for-\nmal peer-review process. This document is intended as a guideline only,\nnot an AAHA or AAFP standard of care. These guidelines and recom-',
  'INFORMED CONSENT\nThis work did not involve the use of animals and, therefore, informed\nconsent was not required. For any animals individually identiﬁable within\nthis publication, informed consent (either verbal or written) for their use in\nthe publication was obtained from the people involved.\nREFERENCES\n1. Flanigan J, Shepherd A, Majchrzak S, et al. US pet ownership and de-\nmographics sourcebook. Schaumburg, IL: American Veterinary Medical\nAssociation, 2007:1–3.\n2. Lue TW, Pantenburg DP, Crawford PM. Impact of the owner-pet and\nclient-veterinarian bond on the care that pets receive. J Am Vet Med\nAssoc 2008;232:531–40.\n3. Volk JO, Felsted KE, Thomas JG, et al. Executive summary of the Bayer\nveterinary care usage study. J Am Vet Med Assoc 2011;238:1275–82.\n4. Bishop G, Cooney K, Cox S, et al. 2016 AAHA/IAAHPC end-of-life care\nguidelines. J Am Anim Hosp Assoc 2016;52:341–56.\n5. AAFP. 2021 AAFP End of Life Online Educational Toolkit. Available at:\ncatvets.com/endoﬂife.\n6. Hoyumpa Vogt A, Rodan I, Brown M, et al. AAFP–AAHA feline life\nstage guidelines. J Feline Med Surg 2010;12:43–54.\n7. Stone AE, Brummet GO, Carozza EM, et al. 2020 AAHA/AAFP feline\nvaccination guidelines. J Feline Med Surg 2020;22:813–30.\n8. Rodan I, Sundahl E, Carney H, et al. AAFP and ISFM feline-friendly\nhandling guidelines. J Feline Med Surg 2011;13:364–75.\n9. Carney HC, Little S, Brownlee-Tomasso D, et al. AAFP and ISFM feline-\nfriendly nursing care guidelines. J Feline Med Surg 2012;14:337–49.\n10. AAFP. AAFP Cat Friendly Certiﬁcate Program. Available at: catvets.com/\ncertiﬁcate.\n11. AAFP. AAFP Cat Friendly Practices. Available at: catvets.com/cfp.\n12. Pittari J, Rodan I, Beekman G, et al. American Association of Feline\nPractitioners. Senior care guidelines. J Feline Med Surg 2009;11:763–78.\n13. AAFP Position Statement. Early spay and castration. Available at: catvets.\ncom/public/PDFs/PositionStatements/EarlySpay&Neuter.pdf.\n14. AAFP. Client brochures for cat owners. How do I know if my cat is in\npain? Available at: https://catvets.com/guidelines/client-brochures.\n15. Gough A, Thomas A, O’Neill D. Part II: cat breeds. In: Gough A,\nThomas A, O’Neill D, eds. Breed predispositions to disease in dogs and\ncats. 3rd ed. Chichester (UK): John Wiley & Sons; 2018:225–55.\n16. Hosie MJ, Addie DD, Boucraut-Baralon C, et al. Matrix vaccination\nguidelines: 2015 ABCD recommendations for indoor/outdoor cats, rescue\nshelter cats and breeding catteries. J Feline Med Surg 2015;17:583–7.\n17. Lappin MR, Elston T, Evans L, et al. 2019 AAFP feline zoonoses\nguidelines. J Feline Med Surg 2019;21:1008–21.\n18. Little S, Levy J, Hartmann K, et al. 2020 AAFP feline retrovirus testing\nand management guidelines. J Feline Med Surg 2020;22:5–30.',
  'by the American Animal Hospital Association (AAHA) and the American\nAssociation of Feline Practitioners (AAFP) and were subjected to a for-\nmal peer-review process. This document is intended as a guideline only,\nnot an AAHA or AAFP standard of care. These guidelines and recom-\nmendations should not be construed as dictating an exclusive protocol,\ncourse of treatment, or procedure. Variations in practice may be war-\nranted based on the needs of the individual patient, resources, and\nlimitations unique to each individual practice setting. Evidence-based\nsupport for speciﬁc recommendations has been cited whenever pos-\nsible and appropriate.\nOther recommendations are based on practical clinical experience and\na consensus of expert opinion. Further research is needed to document\nsome of these recommendations. Because each case is different, vet-\nerinarians must base their decisions on the best available scientiﬁc ev-\nidence in conjunction with their own knowledge and experience.\nBCS (body condition score); DER (daily energy requirements); DJD\n(degenerative joint disease); FCV (feline calicivirus); FeLV (feline leukemia\nvirus); FHV-1 (feline herpesvirus type 1); FIC (feline idiopathic cystitis);\nFPV (feline panleukopenia virus); GI (gastrointestinal); HARD (heartworm-\nassociated respiratory disease); MCS (muscle condition score); RER\n(resting energy requirements); T4 (thyroxine)\nAccepted for publication: October 4, 2020.\nª 2021 by American Animal Hospital Association, American Association of Feline Practitioners, and International Society of Feline Medicine\nJAAHA.ORG\n51'],
 'response': 'Paula\u202fPlummer is one of the authors of the 2021 AAHA/AAFP Feline Life‑Stage Guidelines. She served on the Guideline Task Force (listed alongside the other authors) and is a licensed veterinary technician/veterinary technologist (LVT, VTS).'}

# Run OpenAI RAG Pipeline (with LangSmith)

In [4]:
with tracing_context(project_name=os.environ["LANGSMITH_PROJECT_OPENAI"]):
    openai_graph = get_rag_graph("openai")
    openai_eval_result = run_rag_over_testset(openai_graph, testset_df)


openai_eval_result[0]

{'user_input': 'Who is Paula Plummer in the 2021 AAHA/AAFP Feline Life Stage Guidelines?',
 'reference': 'Paula Plummer, LVT, VTS (ECC, SAIM), is one of the authors of the 2021 AAHA/AAFP Feline Life Stage Guidelines and is affiliated with the Texas A&M University Veterinary Medical Teaching Hospital, College Station, Texas, USA.',
 'reference_contexts': ['VETERINARY PRACTICE GUIDELINES\n2021 AAHA/AAFP Feline Life Stage Guidelines*\nJessica Quimby, DVM, PhD, DACVIMy, Shannon Gowland, DVM, DABVPy, Hazel C. Carney, DVM, MS, DABVP,\nTheresa DePorter, DVM, MRCVS, DACVB, DECAWBM, Paula Plummer, LVT, VTS (ECC, SAIM), Jodi Westropp,\nDVM, PhD, DACVIM\nABSTRACT\nThe guidelines, authored by a Task Force of experts in feline clinical medicine, are an update and extension of the AAFP–AAHA\nFeline Life Stage Guidelines published in 2010. The guidelines are published simultaneously in the Journal of Feline Medicine and\nSurgery (volume 23, issue 3, pages 211–233, DOI: 10.1177/1098612X21993657) and the Journal of the American Animal Hospital\nAssociation (volume 57, issue 2, pages 51–72, DOI: 10.5326/JAAHA-MS-7189). A noteworthy change from the earlier guidelines is\nthe division of the cat’s lifespan into a ﬁve-stage grouping with four distinct age-related stages (kitten, young adult, mature adult,\nand senior) as well as an end-of-life stage, instead of the previous six. This simpliﬁed grouping is consistent with how pet owners\ngenerally perceive their cat’s maturation and aging process, and provides a readily understood basis for an evolving, individualized,\nlifelong feline healthcare strategy. The guidelines include a comprehensive table on the components of a feline wellness visit that\nprovides a framework for systematically implementing an individualized life stage approach to feline healthcare. Included are\nrecommendations for managing the most critical health-related factors in relation to a cat’s life stage. These recommendations are\nfurther explained in the following categories: behavior and environmental needs; elimination; life stage nutrition and weight\nmanagement; oral health; parasite control; vaccination; zoonoses and human safety; and recommended diagnostics based on\nlife stage. A discussion on overcoming barriers to veterinary visits by cat owners offers practical advice on one of the most\nchallenging aspects of delivering regular feline healthcare. (J Am Anim Hosp Assoc 2021; 57:51–72. DOI 10.5326/JAAHA-MS-7189)\nAFFILIATIONS\nThe Ohio State University, Department of Veterinary Clinical Sciences, Co-\nlumbus, Ohio, USA (J.Q.); OVC Smith Lane Animal Hospital, Ontario Vet-\nerinary College, Guelph, Ontario, Canada (S.G.); WestVet Emergency and\nSpecialty Center, Garden City, Idaho, USA (H.C.C.); Oakland Veterinary\nReferral Services, Bloomﬁeld Hills, Michigan, USA (T.D.); Texas A&M Uni-\nversity Veterinary Medical Teaching Hospital, College Station, Texas, USA\n(P.P.); and University of California, Davis, School of Veterinary Medicine,\nDavis, California, USA (J.W.).\nKEYWORDS\nFeline life stage; kitten; adult; senior; veterinary; healthcare examination;\nmedical history; behavior; risk assessment; elimination\nCorrespondence: quimby.19@osu.edu (J.Q.)\n* Boehringer Ingelheim Animal Health USA Inc., CareCredit, Dechra Vet-\nerinary Products, IDEXX Laboratories, Inc., Merck Animal Health, and Zoetis\nPetcare supported the development of the 2021 AAHA/AAFP Feline Life\nStage Guidelines and resources through an educational grant to AAHA.\n† J. Quimby and S. Gowland were cochairs of the 2021 AAHA/AAFP\nFeline Life Stage Guidelines Task Force.\nThese guidelines were prepared by a Task Force of experts convened\nby the American Animal Hospital Association (AAHA) and the American\nAssociation of Feline Practitioners (AAFP) and were subjected to a for-\nmal peer-review process. This document is intended as a guideline only,\nnot an AAHA or AAFP standard of care. These guidelines and recom-'],
 'retrieved_contexts': ['VETERINARY PRACTICE GUIDELINES\n2021 AAHA/AAFP Feline Life Stage Guidelines*\nJessica Quimby, DVM, PhD, DACVIMy, Shannon Gowland, DVM, DABVPy, Hazel C. Carney, DVM, MS, DABVP,\nTheresa DePorter, DVM, MRCVS, DACVB, DECAWBM, Paula Plummer, LVT, VTS (ECC, SAIM), Jodi Westropp,\nDVM, PhD, DACVIM\nABSTRACT\nThe guidelines, authored by a Task Force of experts in feline clinical medicine, are an update and extension of the AAFP–AAHA\nFeline Life Stage Guidelines published in 2010. The guidelines are published simultaneously in the Journal of Feline Medicine and\nSurgery (volume 23, issue 3, pages 211–233, DOI: 10.1177/1098612X21993657) and the Journal of the American Animal Hospital\nAssociation (volume 57, issue 2, pages 51–72, DOI: 10.5326/JAAHA-MS-7189). A noteworthy change from the earlier guidelines is\nthe division of the cat’s lifespan into a ﬁve-stage grouping with four distinct age-related stages (kitten, young adult, mature adult,\nand senior) as well as an end-of-life stage, instead of the previous six. This simpliﬁed grouping is consistent with how pet owners\ngenerally perceive their cat’s maturation and aging process, and provides a readily understood basis for an evolving, individualized,\nlifelong feline healthcare strategy. The guidelines include a comprehensive table on the components of a feline wellness visit that\nprovides a framework for systematically implementing an individualized life stage approach to feline healthcare. Included are\nrecommendations for managing the most critical health-related factors in relation to a cat’s life stage. These recommendations are\nfurther explained in the following categories: behavior and environmental needs; elimination; life stage nutrition and weight\nmanagement; oral health; parasite control; vaccination; zoonoses and human safety; and recommended diagnostics based on\nlife stage. A discussion on overcoming barriers to veterinary visits by cat owners offers practical advice on one of the most\nchallenging aspects of delivering regular feline healthcare. (J Am Anim Hosp Assoc 2021; 57:51–72. DOI 10.5326/JAAHA-MS-7189)\nAFFILIATIONS\nThe Ohio State University, Department of Veterinary Clinical Sciences, Co-\nlumbus, Ohio, USA (J.Q.); OVC Smith Lane Animal Hospital, Ontario Vet-\nerinary College, Guelph, Ontario, Canada (S.G.); WestVet Emergency and\nSpecialty Center, Garden City, Idaho, USA (H.C.C.); Oakland Veterinary\nReferral Services, Bloomﬁeld Hills, Michigan, USA (T.D.); Texas A&M Uni-\nversity Veterinary Medical Teaching Hospital, College Station, Texas, USA\n(P.P.); and University of California, Davis, School of Veterinary Medicine,\nDavis, California, USA (J.W.).\nKEYWORDS\nFeline life stage; kitten; adult; senior; veterinary; healthcare examination;\nmedical history; behavior; risk assessment; elimination\nCorrespondence: quimby.19@osu.edu (J.Q.)\n* Boehringer Ingelheim Animal Health USA Inc., CareCredit, Dechra Vet-\nerinary Products, IDEXX Laboratories, Inc., Merck Animal Health, and Zoetis\nPetcare supported the development of the 2021 AAHA/AAFP Feline Life\nStage Guidelines and resources through an educational grant to AAHA.\n† J. Quimby and S. Gowland were cochairs of the 2021 AAHA/AAFP\nFeline Life Stage Guidelines Task Force.\nThese guidelines were prepared by a Task Force of experts convened\nby the American Animal Hospital Association (AAHA) and the American\nAssociation of Feline Practitioners (AAFP) and were subjected to a for-\nmal peer-review process. This document is intended as a guideline only,\nnot an AAHA or AAFP standard of care. These guidelines and recom-',
  'TABLE 2 (Continued)\n2021 AAHA/AAFP Feline Life Stage Guidelines\nJAAHA.ORG\n55',
  'events to increase knowledge and conﬁdence when taking patient\nhistories (see “Conducting Effective Patient Histories” box) and pro-\nviding client education are just as important as further education on\nfeline-friendly handling, disease processes, and technical skills.\nIdeally, client education is a key responsibility for all staff\nmembers. Every life stage will have speciﬁc items that should be\ndiscussed in the veterinary visit (see Table 2), and both veterinary\ntechnicians and veterinarians should be familiar with current rec-\nommendations and practice protocols in order to educate clients on\nthe most critical health-related factors relevant to each life stage.\nThe practice team can better connect with clients when they un-\nderstand that pet owners can become overwhelmed at veterinary\nvisits. Moreover, communicating that the cat owner is an integral\npart of the healthcare team can reinforce the veterinary-client-\npatient relationship, as well as improve compliance.\nSummary\nThe 2021 AAHA/AAFP Feline Life Stage Guidelines deﬁne four distinct age-\nrelated feline life stages: kitten (birth up to 1 year), young adult (1–6\nyears), mature adult (7–10 years), and senior (greater than 10 years). End\nof life and its precursor events are a ﬁfth life stage that is not age speciﬁc,\nand are discussed in separate 2016 AAHA/IAAHPC End-of-Life Care\nGuidelines4 and the 2021 AAFP End of Life Online Educational Toolkit.5\nWithin these 2021 AAHA/AAFP Feline Life Stage Guidelines, the Task Force\noffers evidence-guided recommendations for eight clinical aspects of feline\nmedicine that should be managed in relation to a cat’s life stage: behavior\nand environmental needs; elimination; nutrition and weight management;\noral health; parasite control; vaccination; zoonoses and human safety; and\ndiagnostics. Additionally, important topics include feline-friendly handling\npractices, overcoming barriers to examination visits, environmental en-\nrichment, understanding feline behavior, practice team training, and client\neducation. Integrating clinical management with appropriate patient\nhandling, and practice team and client collaboration, all tailored to the\ncat’s life stage, forms the basis for an effective, individualized healthcare\nstrategy that can be applied throughout the feline patient’s lifetime.\nThe Task Force gratefully acknowledges the contribution of\nMark Dana of Scientiﬁc Communications Services, LLC, and\nthe Kanara Consulting Group, LLC, in the preparation of the\nguidelines manuscript.\nCONFLICT OF INTEREST\nHazel C. Carney has received speaking fees from Royal Canin. Jessica\nQuimby is a consultant/key opinion leader for Boehringer Ingelheim\nAnimal Health USA Inc., Dechra Veterinary Products, Elanco Animal\nHealth, Hill’s Pet Nutrition, Inc., IDEXX Laboratories, Inc., Kindred\nBiosciences, Inc., Nestlé Purina Petcare, and Royal Canin. Jodi Westropp\nhas received speaking fees from Bayer Animal Health, Nestlé Purina\nPetcare, Hill’s Pet Nutrition, Inc., and Royal Canin; served as a consultant/\nkey opinion leader for Nestlé Purina Petcare; and served on the academic\nboard for the International School of Veterinary Postgraduate Studies. The\nother members of the Task Force have no conﬂicts of interest to declare.\nFUNDING\nBoehringer Ingelheim Animal Health USA Inc., CareCredit, Dechra\nVeterinary Products, IDEXX Laboratories, Inc., Merck Animal Health,\nand Zoetis Petcare supported the development of the 2021 AAHA/\nAAFP Feline Life Stage Guidelines and resources through an educa-\ntional grant to AAHA.\nETHICAL APPROVAL\nThis work did not involve the use of animals and, therefore, ethical\napproval was not speciﬁcally required for publication.\nAdditional Client Education Resources\nClient communication can be optimized by using online literature,\nhandouts, and tools. To help educate clients about the importance of an\nindividualized, lifelong healthcare strategy for their cat, both AAHA and the\nAAFP have handouts available to members and non-members. Addi-',
  'Introduction\nThe feline patient’s life stage is the most fundamental presentation\nfactor the practitioner encounters in a regular examination visit.\nMost of the components of a treatment or healthcare plan are\nguided by the patient’s life stage, progressing from kitten to young\nadult, mature adult, and senior and concluding with the end-of-life\nstage. Because a cat can transition from one life stage to another in a\nshort period of time, each examination visit should include a life\nstage assessment. The 2021 AAHA/AAFP Feline Life Stage Guidelines\nprovide a comprehensive age-associated framework for promoting\nhealth and longevity throughout a cat’s lifetime. The guidelines were\ndeveloped by a Task Force of experts in feline clinical medicine.\nTheir recommendations are a practical resource to guide individu-\nalized risk assessment, preventive healthcare strategies, and treat-\nment pathways that evolve as the cat matures.\nAn evidence-guided framework for managing a cat’s healthcare\nthroughout its lifetime has never been more important in feline\npractice than it is now. Cats are the most popular pet in the United\nStates.1 A great anomaly in feline practice is that although most\nowners consider their cats to be family members, cats are sub-\nstantially underserved in the primary care setting compared with\ndogs.2 In 2006, owners took their dogs to veterinarians more than\ntwice as often as cats: 2.3 times/year for dogs versus 1.1 times/year\nfor cats.3 This healthcare use imbalance persists to the present day.\nCat owners often express a belief that their pets “do not need\nmedical care.” Two reasons for this misconception are that signs of\nillness and pain are often difﬁcult to detect in the sometimes re-\nclusive or stoic cat, and that cats are perceived to be self-sufﬁcient.\nSpeciﬁc objectives of the guidelines are (1) to deﬁne distinct\nfeline life stages consistent with how pet owners generally perceive\nTABLE 1\nFeline Life Stages\nª Voren1/iStock, spxChrome/E+, AaronAmat/iStock, AngiePhotos/iStock via Getty Images Plus\n52\nJAAHA\n|\n57:2\nMar/Apr 2021'],
 'response': 'Paula Plummer, LVT, VTS (ECC, SAIM), is one of the authors of the 2021 AAHA/AAFP Feline Life Stage Guidelines and is affiliated with the Texas A&M University Veterinary Medical Teaching Hospital, College Station, Texas, USA.'}

## Side-by-side response preview

Compare Fireworks and OpenAI answers on the same test questions before RAGAS scoring.

In [5]:
comparison_df = pd.DataFrame(
    {
        "user_input": [row["user_input"] for row in firework_eval_result],
        "reference": [row["reference"] for row in firework_eval_result],
        "fireworks_response": [row["response"] for row in firework_eval_result],
        "openai_response": [row["response"] for row in openai_eval_result],
        "fireworks_retrieved_chunks": [
            len(row["retrieved_contexts"]) for row in firework_eval_result
        ],
        "openai_retrieved_chunks": [
            len(row["retrieved_contexts"]) for row in openai_eval_result
        ],
    }
)

comparison_df

,user_input,reference,fireworks_response,openai_response,fireworks_retrieved_chunks,openai_retrieved_chunks
0,Who is Paula Plummer in the 2021 AAHA/AAFP Fel...,"Paula Plummer, LVT, VTS (ECC, SAIM), is one of...",Paula Plummer is one of the authors of the 202...,"Paula Plummer, LVT, VTS (ECC, SAIM), is one of...",4,4
1,how feline retrovirus testing and management l...,The 2020 AAFP feline retrovirus testing and ma...,The excerpt lists **the 2020 AAFP Feline Retro...,Feline retrovirus testing and management and f...,4,4
2,What are the recommended litter box management...,"For kittens, it is recommended to discuss appr...",**Litter‑box management for kittens (to keep t...,The recommended litter box management practice...,4,4

## RAGAS Scoring

In [6]:
# Score Fireworks rows
fireworks_scores = score_rag_rows_sync(firework_eval_result)

# Summarize scores
summarize_scores(fireworks_scores)

context_recall     0.833333
faithfulness       0.777778
answer_accuracy    0.750000
dtype: float64

In [7]:
# Score OpenAI rows
openai_scores = score_rag_rows_sync(openai_eval_result)

# Summarize scores
summarize_scores(openai_scores)

context_recall     0.833333
faithfulness       0.666667
answer_accuracy    0.666667
dtype: float64

## compare scores

In [8]:
compare_providers(fireworks_scores, openai_scores)

                 fireworks    openai
context_recall    0.833333  0.833333
faithfulness      0.777778  0.666667
answer_accuracy   0.750000  0.666667

## LangSmith Cost Analysis

Fill in `estimated_cost_usd` and `notes` from the [LangSmith dashboard](https://smith.langchain.com) for each project. Token counts are pulled automatically when traces exist.

In [9]:
from langsmith import Client


def _project_token_stats(project_name: str) -> dict[str, int | str | None]:
    try:
        client = Client()
        runs = list(client.list_runs(project_name=project_name, limit=100))
        return {
            "run_count": len(runs),
            "prompt_tokens": sum(r.prompt_tokens or 0 for r in runs),
            "completion_tokens": sum(r.completion_tokens or 0 for r in runs),
            "total_tokens": sum(r.total_tokens or 0 for r in runs),
            "notes": "",
        }
    except Exception as exc:
        return {
            "run_count": None,
            "prompt_tokens": None,
            "completion_tokens": None,
            "total_tokens": None,
            "notes": f"Could not load runs: {exc}",
        }


cost_rows = []
for provider, env_key in [
    ("Fireworks", "LANGSMITH_PROJECT_FIREWORKS"),
    ("OpenAI", "LANGSMITH_PROJECT_OPENAI"),
]:
    project_name = os.environ[env_key]
    stats = _project_token_stats(project_name)
    cost_rows.append(
        {
            "provider": provider,
            "project_name": project_name,
            "run_count": stats["run_count"],
            "prompt_tokens": stats["prompt_tokens"],
            "completion_tokens": stats["completion_tokens"],
            "total_tokens": stats["total_tokens"],
            "estimated_cost_usd": None,
            "notes": stats["notes"],
        }
    )

cost_analysis_df = pd.DataFrame(cost_rows)
cost_analysis_df

,provider,project_name,run_count,prompt_tokens,completion_tokens,total_tokens,estimated_cost_usd,notes
0,Fireworks,llm-servers-fireworks-rag,100,46176,7620,53796,None,
1,OpenAI,llm-servers-openai-rag,24,43352,2288,45640,None,